[2018-11-03 23:43:48 +0800] [25179] [INFO] Starting gunicorn 19.9.0
[2018-11-03 23:43:48 +0800] [25179] [INFO] Listening at: http://127.0.0.1:8000 (25179)
[2018-11-03 23:43:48 +0800] [25179] [INFO] Using worker: sync
[2018-11-03 23:43:48 +0800] [25187] [INFO] Booting worker with pid: 25187
[2018-11-03 23:43:49 +0800] [25188] [INFO] Booting worker with pid: 25188
[2018-11-03 23:43:49 +0800] [25189] [INFO] Booting worker with pid: 25189
[2018-11-03 23:43:49 +0800] [25190] [INFO] Booting worker with pid: 25190
[2018-11-03 23:43:57 +0800] [25204] [INFO] Starting gunicorn 19.9.0
[2018-11-03 23:43:57 +0800] [25204] [ERROR] Connection in use: ('127.0.0.1', 8000)
[2018-11-03 23:43:57 +0800] [25204] [ERROR] Retrying in 1 second.
[2018-11-03 23:43:58 +0800] [25204] [ERROR] Connection in use: ('127.0.0.1', 8000)
[2018-11-03 23:43:58 +0800] [25204] [ERROR] Retrying in 1 second.
[2018-11-03 23:43:59 +0800] [25204] [ERROR] Connection in use: ('127.0.0.1', 8000)
[2018-11-03 23:43:59 +0800] [25204] [ERROR] Retrying in 1 second.
[2018-11-03 23:44:00 +0800] [25204] [ERROR] Connection in use: ('127.0.0.1', 8000)
[2018-11-03 23:44:00 +0800] [25204] [ERROR] Retrying in 1 second.
[2018-11-03 23:44:01 +0800] [25204] [ERROR] Connection in use: ('127.0.0.1', 8000)
[2018-11-03 23:44:01 +0800] [25204] [ERROR] Retrying in 1 second.
[2018-11-03 23:44:02 +0800] [25204] [ERROR] Can't connect to ('127.0.0.1', 8000)
[2018-11-03 23:54:47 +0800] [25699] [INFO] Starting gunicorn 19.9.0
[2018-11-03 23:54:47 +0800] [25699] [ERROR] Connection in use: ('127.0.0.1', 8000)
[2018-11-03 23:54:47 +0800] [25699] [ERROR] Retrying in 1 second.
[2018-11-03 23:54:48 +0800] [25699] [ERROR] Connection in use: ('127.0.0.1', 8000)
[2018-11-03 23:54:48 +0800] [25699] [ERROR] Retrying in 1 second.
[2018-11-03 23:54:49 +0800] [25699] [ERROR] Connection in use: ('127.0.0.1', 8000)
[2018-11-03 23:54:49 +0800] [25699] [ERROR] Retrying in 1 second.
[2018-11-03 23:54:50 +0800] [25699] [ERROR] Connection in use: ('127.0.0.1', 8000)
[2018-11-03 23:54:50 +0800] [25699] [ERROR] Retrying in 1 second.
[2018-11-03 23:54:51 +0800] [25699] [ERROR] Connection in use: ('127.0.0.1', 8000)
[2018-11-03 23:54:51 +0800] [25699] [ERROR] Retrying in 1 second.
[2018-11-03 23:54:52 +0800] [25699] [ERROR] Can't connect to ('127.0.0.1', 8000)
[2018-11-04 00:18:47 +0800] [25179] [INFO] Handling signal: hup
[2018-11-04 00:18:47 +0800] [25179] [INFO] Hang up: Master
[2018-11-04 00:18:48 +0800] [26829] [INFO] Booting worker with pid: 26829
[2018-11-04 00:18:48 +0800] [26831] [INFO] Booting worker with pid: 26831
[2018-11-04 00:18:48 +0800] [26830] [INFO] Booting worker with pid: 26830
[2018-11-04 00:18:48 +0800] [26833] [INFO] Booting worker with pid: 26833
[2018-11-04 00:18:48 +0800] [25179] [INFO] Handling signal: term
[2018-11-04 00:19:18 +0800] [25179] [INFO] Shutting down: Master
[2018-11-04 09:45:26 +0800] [4741] [INFO] Starting gunicorn 19.9.0
[2018-11-04 09:45:26 +0800] [4741] [INFO] Listening at: http://127.0.0.1:8000 (4741)
[2018-11-04 09:45:26 +0800] [4741] [INFO] Using worker: sync
[2018-11-04 09:45:26 +0800] [4744] [INFO] Booting worker with pid: 4744
[2018-11-04 09:45:26 +0800] [4744] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/yapie/github/Django-pro/blog_project/venv/lib/python3.5/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/home/yapie/github/Django-pro/blog_project/venv/lib/python3.5/site-packages/gunicorn/workers/base.py", line 129, in init_process
    self.load_wsgi()
  File "/home/yapie/github/Django-pro/blog_project/venv/lib/python3.5/site-packages/gunicorn/workers/base.py", line 138, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/yapie/github/Django-pro/blog_project/venv/lib/python3.5/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/yapie/github/Django-pro/blog_project/venv/lib/python3.5/site-packages/gunicorn/app/wsgiapp.py", line 52, in load
    return self.load_wsgiapp()
  File "/home/yapie/github/Django-pro/blog_project/venv/lib/python3.5/site-packages/gunicorn/app/wsgiapp.py", line 41, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/yapie/github/Django-pro/blog_project/venv/lib/python3.5/site-packages/gunicorn/util.py", line 350, in import_app
    __import__(module)
ImportError: No module named 'help'
[2018-11-04 09:45:26 +0800] [4744] [INFO] Worker exiting (pid: 4744)
[2018-11-04 09:45:27 +0800] [4745] [INFO] Booting worker with pid: 4745
[2018-11-04 09:45:27 +0800] [4745] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/home/yapie/github/Django-pro/blog_project/venv/lib/python3.5/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/home/yapie/github/Django-pro/blog_project/venv/lib/python3.5/site-packages/gunicorn/workers/base.py", line 129, in init_process
    self.load_wsgi()
  File "/home/yapie/github/Django-pro/blog_project/venv/lib/python3.5/site-packages/gunicorn/workers/base.py", line 138, in load_wsgi
    self.wsgi = self.app.wsgi()
  File "/home/yapie/github/Django-pro/blog_project/venv/lib/python3.5/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
  File "/home/yapie/github/Django-pro/blog_project/venv/lib/python3.5/site-packages/gunicorn/app/wsgiapp.py", line 52, in load
    return self.load_wsgiapp()
  File "/home/yapie/github/Django-pro/blog_project/venv/lib/python3.5/site-packages/gunicorn/app/wsgiapp.py", line 41, in load_wsgiapp
    return util.import_app(self.app_uri)
  File "/home/yapie/github/Django-pro/blog_project/venv/lib/python3.5/site-packages/gunicorn/util.py", line 350, in import_app
    __import__(module)
ImportError: No module named 'help'
[2018-11-04 09:45:27 +0800] [4745] [INFO] Worker exiting (pid: 4745)
[2018-11-04 09:45:27 +0800] [4741] [INFO] Shutting down: Master
[2018-11-04 09:45:27 +0800] [4741] [INFO] Reason: Worker failed to boot.
[2018-11-04 09:46:48 +0800] [5257] [INFO] Starting gunicorn 19.9.0
[2018-11-04 09:46:48 +0800] [5257] [INFO] Listening at: http://127.0.0.1:8000 (5257)
[2018-11-04 09:46:48 +0800] [5257] [INFO] Using worker: sync
[2018-11-04 09:46:48 +0800] [5260] [INFO] Booting worker with pid: 5260
[2018-11-04 09:46:49 +0800] [5261] [INFO] Booting worker with pid: 5261
[2018-11-04 09:46:49 +0800] [5262] [INFO] Booting worker with pid: 5262
[2018-11-04 09:46:49 +0800] [5265] [INFO] Booting worker with pid: 5265
[2018-11-04 10:12:57 +0800] [5257] [INFO] Handling signal: int
[2018-11-04 10:12:57 +0800] [5257] [INFO] Shutting down: Master
[2018-11-04 10:15:58 +0800] [9512] [INFO] Starting gunicorn 19.9.0
[2018-11-04 10:15:58 +0800] [9512] [INFO] Listening at: http://127.0.0.1:8000 (9512)
[2018-11-04 10:15:58 +0800] [9512] [INFO] Using worker: sync
[2018-11-04 10:15:58 +0800] [9520] [INFO] Booting worker with pid: 9520
[2018-11-04 10:15:58 +0800] [9521] [INFO] Booting worker with pid: 9521
[2018-11-04 10:15:58 +0800] [9523] [INFO] Booting worker with pid: 9523
[2018-11-04 10:15:58 +0800] [9525] [INFO] Booting worker with pid: 9525
[2018-11-04 10:32:20 +0800] [9512] [INFO] Handling signal: hup
[2018-11-04 10:32:20 +0800] [9512] [INFO] Hang up: Master
[2018-11-04 10:32:20 +0800] [12289] [INFO] Booting worker with pid: 12289
[2018-11-04 10:32:20 +0800] [12291] [INFO] Booting worker with pid: 12291
[2018-11-04 10:32:20 +0800] [12290] [INFO] Booting worker with pid: 12290
[2018-11-04 10:32:20 +0800] [12292] [INFO] Booting worker with pid: 12292
